[package]
name = "user-fund-storage"
version = "0.5.8"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2018"
[dependencies.dharitri-sc]
version = "0.0.3"
[dev-dependencies.dharitri-sc-scenario]
version = "0.0.3"
